/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_exobel_routerkeygen_NativeThomson */

#ifndef _Included_org_exobel_routerkeygen_NativeThomson
#define _Included_org_exobel_routerkeygen_NativeThomson
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_exobel_routerkeygen_NativeThomson
 * Method:    thomson
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_exobel_routerkeygen_NativeThomson_thomson
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
