package org.exobel.routerkeygen;

public class unkown {
	static char charect[] = { 
		(char) 'A', (char) 'B', (char) 'C', (char) 'D',
		(char) 'E', (char) 'F', (char) 'G', (char) 'H', 
		(char) 'I', (char) 'J', (char) 'K', (char) 'L',
		(char) 'M', (char) 'N', (char) 'O', (char) 'P', 
	    (char) 'Q', (char) 'R', (char) 'S', (char) 'T',
	    (char) 'U', (char) 'V', (char) 'W', (char) 'X', 
		(char) 'Y', (char) 'Z', (char) '0', (char) '1',
		(char) '2', (char) '3', (char) '4', (char) '5', 
		(char) '6', (char) '7', (char) '8', (char) '9'
		};

    static byte[][] charectbytes = {
        new byte[]{ '3', '0'},
        new byte[]{ '3', '1'},
        new byte[]{ '3', '2'},
        new byte[]{ '3', '3'},
        new byte[]{ '3', '4'},
        new byte[]{ '3', '5'},
        new byte[]{ '3', '6'},
        new byte[]{ '3', '7'},
        new byte[]{ '3', '8'},
        new byte[]{ '3', '9'},
        new byte[]{ '4', '1'},
        new byte[]{ '4', '2'},
        new byte[]{ '4', '3'},
        new byte[]{ '4', '4'},
        new byte[]{ '4', '5'},
        new byte[]{ '4', '6'},
        new byte[]{ '4', '7'},
        new byte[]{ '4', '8'},
        new byte[]{ '4', '9'},
        new byte[]{ '4', 'A'},
        new byte[]{ '4', 'B'},
        new byte[]{ '4', 'C'},
        new byte[]{ '4', 'D'},
        new byte[]{ '4', 'E'},
        new byte[]{ '4', 'F'},
        new byte[]{ '5', '0'},
        new byte[]{ '5', '1'},
        new byte[]{ '5', '2'},
        new byte[]{ '5', '3'},
        new byte[]{ '5', '4'},
        new byte[]{ '5', '5'},
        new byte[]{ '5', '6'},
        new byte[]{ '5', '7'},
        new byte[]{ '5', '8'},
        new byte[]{ '5', '9'},
        new byte[]{ '5', 'A'},
        };
    
    static byte[] charectbytes0 = {
        '3',
        '3',
        '3',
        '3',
        '3',
        '3',
        '3',
        '3',
        '3',
        '3',
    	'4',
        '4',
        '4',
        '4',
        '4',
        '4',
        '4',
        '4',
        '4',
        '4',
        '4',
        '4',
        '4',
        '4',
        '4',
        '5',
        '5',
        '5',
        '5',
        '5',
        '5',
        '5',
        '5',
        '5',
        '5',
        '5',
        };
    
    static byte[] charectbytes1 = {
        '0',
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        '0',
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        'A',
        };
}
