/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_exobel_routerkeygen_Hash */

#ifndef _Included_org_exobel_routerkeygen_Hash
#define _Included_org_exobel_routerkeygen_Hash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_exobel_routerkeygen_Hash
 * Method:    hashword
 * Signature: ([III)I
 */
JNIEXPORT jint JNICALL Java_org_exobel_routerkeygen_Hash_hashword
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     org_exobel_routerkeygen_Hash
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_exobel_routerkeygen_Hash_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
